#!/bin/bash
# install-hooks.sh - Install version-controlled git hooks from .wrangler/git-hooks/
# Generated by wrangler git-hooks framework (Pattern B)
#
# Usage:
#   ./scripts/install-hooks.sh
#
# This script creates symlinks from .git/hooks/ to .wrangler/git-hooks/
# enabling version-controlled hooks that stay synchronized across team.

set -e

# =============================================================================
# Configuration
# =============================================================================
HOOKS_SOURCE_DIR=".wrangler/git-hooks"
HOOKS_TARGET_DIR=".git/hooks"
HOOKS=("pre-commit" "pre-push" "commit-msg")

# =============================================================================
# Logging helpers
# =============================================================================
log_info() {
    echo "[install-hooks] INFO: $1"
}

log_success() {
    echo "[install-hooks] OK: $1"
}

log_error() {
    echo "[install-hooks] ERROR: $1" >&2
}

log_warn() {
    echo "[install-hooks] WARN: $1"
}

# =============================================================================
# Pre-flight checks
# =============================================================================
log_info "Installing git hooks from $HOOKS_SOURCE_DIR..."
echo ""

# Check if we're in a git repository
if ! git rev-parse --show-toplevel > /dev/null 2>&1; then
    log_error "Not in a git repository"
    log_error "Run this script from within a git repository"
    exit 1
fi

# Get git root (handles running from subdirectory)
GIT_ROOT=$(git rev-parse --show-toplevel)
cd "$GIT_ROOT"

# Check if source directory exists
if [ ! -d "$HOOKS_SOURCE_DIR" ]; then
    log_error "Hooks source directory not found: $HOOKS_SOURCE_DIR"
    log_error ""
    log_error "Expected directory structure:"
    log_error "  $HOOKS_SOURCE_DIR/"
    log_error "  ├── pre-commit"
    log_error "  ├── pre-push"
    log_error "  └── commit-msg"
    log_error ""
    log_error "Run /wrangler:setup-git-hooks with Pattern B to create this structure."
    exit 1
fi

# Check if .git directory exists
if [ ! -d ".git" ]; then
    log_error ".git directory not found"
    log_error "Are you sure this is a git repository?"
    exit 1
fi

# Ensure hooks target directory exists
mkdir -p "$HOOKS_TARGET_DIR"

# =============================================================================
# Backup existing hooks
# =============================================================================
BACKUP_DIR=".git/hooks.backup.$(date +%Y%m%d%H%M%S)"
BACKED_UP=false

for hook in "${HOOKS[@]}"; do
    target="$HOOKS_TARGET_DIR/$hook"
    if [ -f "$target" ] && [ ! -L "$target" ]; then
        if [ "$BACKED_UP" = false ]; then
            mkdir -p "$BACKUP_DIR"
            log_info "Backing up existing hooks to $BACKUP_DIR/"
            BACKED_UP=true
        fi
        cp "$target" "$BACKUP_DIR/"
        log_info "  Backed up: $hook"
    fi
done

if [ "$BACKED_UP" = true ]; then
    echo ""
fi

# =============================================================================
# Install hooks via symlinks
# =============================================================================
log_info "Creating symlinks..."
installed_count=0
skipped_count=0

for hook in "${HOOKS[@]}"; do
    source="$HOOKS_SOURCE_DIR/$hook"
    target="$HOOKS_TARGET_DIR/$hook"

    if [ -f "$source" ]; then
        # Remove existing hook/symlink
        if [ -e "$target" ] || [ -L "$target" ]; then
            rm "$target"
        fi

        # Create relative symlink
        # From .git/hooks/ to .wrangler/git-hooks/, we need ../../.wrangler/git-hooks/
        ln -s "../../$source" "$target"

        # Verify symlink
        if [ -L "$target" ] && [ -e "$target" ]; then
            log_success "  $hook -> $source"
            installed_count=$((installed_count + 1))
        else
            log_error "  Failed to create symlink for $hook"
        fi
    else
        log_warn "  $hook not found in source directory - skipping"
        skipped_count=$((skipped_count + 1))
    fi
done

echo ""

# =============================================================================
# Verify and make executable
# =============================================================================
log_info "Setting executable permissions..."

for hook in "${HOOKS[@]}"; do
    source="$HOOKS_SOURCE_DIR/$hook"
    if [ -f "$source" ]; then
        chmod +x "$source"
        log_success "  $hook"
    fi
done

echo ""

# =============================================================================
# Summary
# =============================================================================
echo "=========================================="
echo "[install-hooks] Installation Complete"
echo "=========================================="
echo ""
echo "  Hooks installed: $installed_count"
echo "  Hooks skipped:   $skipped_count"
if [ "$BACKED_UP" = true ]; then
    echo "  Backup location: $BACKUP_DIR"
fi
echo ""

if [ $installed_count -eq 0 ]; then
    log_warn "No hooks were installed!"
    log_warn "Make sure hooks exist in $HOOKS_SOURCE_DIR/"
    exit 1
fi

log_success "Git hooks are now active"
echo ""
echo "To bypass hooks temporarily (e.g., TDD RED phase):"
echo "  WRANGLER_SKIP_HOOKS=1 git commit -m 'message'"
echo ""
echo "To update hooks, edit files in $HOOKS_SOURCE_DIR/ and re-run this script."
