#!/bin/bash
# Pre-commit hook - Runs formatting, linting, and unit tests before each commit
# Generated by wrangler git-hooks framework
# Configuration: .wrangler/config/hooks-config.json

set -e

# =============================================================================
# Ensure we're at git repository root
# =============================================================================
git_root=$(git rev-parse --show-toplevel 2>/dev/null)
if [ $? -ne 0 ] || [ -z "$git_root" ] || [ ! -d "$git_root" ]; then
    echo "[pre-commit] ERROR: Not in a git repository" >&2
    exit 1
fi
cd "$git_root" || exit 1

# =============================================================================
# Configuration (populated by setup-git-hooks skill)
# =============================================================================
FORMAT_COMMAND="{{FORMAT_COMMAND}}"
LINT_COMMAND="{{LINT_COMMAND}}"
UNIT_TEST_COMMAND="{{UNIT_TEST_COMMAND}}"
DOCS_PATTERNS="{{DOCS_PATTERNS}}"
BYPASS_ENV_VAR="${WRANGLER_SKIP_HOOKS:-}"
SKIP_DOCS_ONLY="${SKIP_DOCS_ONLY:-true}"

# =============================================================================
# Logging helpers
# =============================================================================
log_info() {
    echo "[pre-commit] INFO: $1"
}

log_success() {
    echo "[pre-commit] OK: $1"
}

log_error() {
    echo "[pre-commit] ERROR: $1" >&2
}

log_warn() {
    echo "[pre-commit] WARN: $1"
}

log_step() {
    echo ""
    echo "=========================================="
    echo "[pre-commit] $1"
    echo "=========================================="
}

# =============================================================================
# Bypass mechanism - allows users to skip hooks when needed
# =============================================================================
if [ -n "$BYPASS_ENV_VAR" ]; then
    log_warn "WRANGLER_SKIP_HOOKS is set - bypassing pre-commit checks"
    log_warn "Use this sparingly (e.g., TDD RED phase, emergency fixes)"
    exit 0
fi

# =============================================================================
# Check if setup is complete (handles empty projects)
# =============================================================================
if [ -f ".wrangler/config/hooks-config.json" ]; then
    SETUP_COMPLETE=$(grep -o '"setupComplete"[[:space:]]*:[[:space:]]*true' .wrangler/config/hooks-config.json || echo "false")

    if [ "$SETUP_COMPLETE" = "false" ]; then
        log_info "Git hooks inactive (no tests configured yet)"
        log_info "Run /wrangler:update-git-hooks after adding tests"
        exit 0
    fi
fi

# =============================================================================
# Docs-only detection - skip tests if only documentation changed
# =============================================================================
is_docs_only_change() {
    # Get list of staged files
    staged_files=$(git diff --cached --name-only --diff-filter=ACMR)

    if [ -z "$staged_files" ]; then
        # No staged files, nothing to check
        return 1
    fi

    # Default docs patterns if not configured
    if [ -z "$DOCS_PATTERNS" ] || [ "$DOCS_PATTERNS" = "{{DOCS_PATTERNS}}" ]; then
        DOCS_PATTERNS="*.md *.txt *.rst docs/* README* LICENSE* CHANGELOG*"
    fi

    # Check each staged file against docs patterns
    # Use while loop to handle filenames with spaces correctly
    echo "$staged_files" | while IFS= read -r file; do
        if [ -z "$file" ]; then
            continue
        fi

        is_doc=false
        for pattern in $DOCS_PATTERNS; do
            case "$file" in
                $pattern)
                    is_doc=true
                    break
                    ;;
            esac
        done

        if [ "$is_doc" = false ]; then
            # Found a non-doc file, this is not a docs-only change
            return 1
        fi
    done

    # All files matched docs patterns
    return 0
}

if [ "$SKIP_DOCS_ONLY" = "true" ] && is_docs_only_change; then
    log_info "Docs-only change detected - skipping tests"
    log_info "Files: $(git diff --cached --name-only --diff-filter=ACMR | tr '\n' ' ')"
    exit 0
fi

# =============================================================================
# Capture originally staged files (before any modifications)
# =============================================================================
originally_staged_files=$(git diff --cached --name-only --diff-filter=ACMR)

# =============================================================================
# Step 1: Run formatter (auto-fix and re-stage)
# =============================================================================
if [ -n "$FORMAT_COMMAND" ] && [ "$FORMAT_COMMAND" != "{{FORMAT_COMMAND}}" ]; then
    log_step "Running formatter"
    log_info "Command: $FORMAT_COMMAND"

    if eval "$FORMAT_COMMAND"; then
        log_success "Formatting complete"

        # Re-stage only the originally staged files (not all modified files)
        # Note: We check if file exists (-f) to handle deleted files gracefully.
        # Deleted files don't need re-staging; their deletion is already staged.
        if [ -n "$originally_staged_files" ]; then
            # Use while loop to handle filenames with spaces correctly
            echo "$originally_staged_files" | while IFS= read -r file; do
                if [ -z "$file" ]; then
                    continue
                fi
                if [ ! -f "$file" ]; then
                    log_warn "File $file was modified/deleted during formatting - skipping re-stage"
                    continue
                fi
                git add "$file"
            done
            log_info "Re-staged formatted files"
        fi
    else
        log_error "Formatter failed"
        log_error ""
        log_error "To fix:"
        log_error "  1. Review formatter output above"
        log_error "  2. Fix any formatting errors manually"
        log_error "  3. Stage changes: git add <files>"
        log_error "  4. Try commit again"
        log_error ""
        log_error "To bypass (use sparingly):"
        log_error "  WRANGLER_SKIP_HOOKS=1 git commit -m 'message'"
        exit 1
    fi
else
    log_info "No formatter configured - skipping"
fi

# =============================================================================
# Step 2: Run linter (blocking on failure)
# =============================================================================
if [ -n "$LINT_COMMAND" ] && [ "$LINT_COMMAND" != "{{LINT_COMMAND}}" ]; then
    log_step "Running linter"
    log_info "Command: $LINT_COMMAND"

    if eval "$LINT_COMMAND"; then
        log_success "Linting passed"
    else
        log_error "Linting failed"
        log_error ""
        log_error "To fix:"
        log_error "  1. Review linter output above"
        log_error "  2. Fix all linting errors"
        log_error "  3. Stage changes: git add <files>"
        log_error "  4. Try commit again"
        log_error ""
        log_error "To bypass (use sparingly):"
        log_error "  WRANGLER_SKIP_HOOKS=1 git commit -m 'message'"
        exit 1
    fi
else
    log_info "No linter configured - skipping"
fi

# =============================================================================
# Step 3: Run unit tests (blocking on failure)
# =============================================================================
if [ -n "$UNIT_TEST_COMMAND" ] && [ "$UNIT_TEST_COMMAND" != "{{UNIT_TEST_COMMAND}}" ]; then
    log_step "Running unit tests"
    log_info "Command: $UNIT_TEST_COMMAND"

    start_time=$(date +%s)

    if eval "$UNIT_TEST_COMMAND"; then
        end_time=$(date +%s)
        duration=$((end_time - start_time))
        log_success "Unit tests passed (${duration}s)"

        if [ "$duration" -gt 30 ]; then
            log_warn "Tests took ${duration}s - consider optimizing for faster feedback"
        fi
    else
        log_error "Unit tests failed"
        log_error ""
        log_error "To fix:"
        log_error "  1. Review test output above"
        log_error "  2. Fix failing tests"
        log_error "  3. Try commit again"
        log_error ""
        log_error "For TDD RED phase (writing failing test first):"
        log_error "  WRANGLER_SKIP_HOOKS=1 git commit -m 'WIP: failing test for feature X'"
        log_error ""
        log_error "Note: AI agents cannot use this bypass - only humans."
        exit 1
    fi
else
    log_info "No unit test command configured - skipping"
fi

# =============================================================================
# Success
# =============================================================================
log_step "Pre-commit checks passed"
log_success "All checks passed - proceeding with commit"
exit 0
