#!/bin/bash
# Pre-push hook - Runs full test suite before pushing to protected branches
# Generated by wrangler git-hooks framework
# Configuration: .wrangler/config/hooks-config.json

set -e

# =============================================================================
# Ensure we're at git repository root
# =============================================================================
git_root=$(git rev-parse --show-toplevel 2>/dev/null)
if [ $? -ne 0 ] || [ -z "$git_root" ] || [ ! -d "$git_root" ]; then
    echo "[pre-push] ERROR: Not in a git repository" >&2
    exit 1
fi
cd "$git_root" || exit 1

# =============================================================================
# Configuration (populated by setup-git-hooks skill)
# =============================================================================
TEST_COMMAND="{{TEST_COMMAND}}"
PROTECTED_BRANCHES="{{PROTECTED_BRANCHES}}"
BYPASS_ENV_VAR="${WRANGLER_SKIP_HOOKS:-}"

# Remote and URL passed as arguments
REMOTE="$1"
URL="$2"

# =============================================================================
# Logging helpers
# =============================================================================
log_info() {
    echo "[pre-push] INFO: $1"
}

log_success() {
    echo "[pre-push] OK: $1"
}

log_error() {
    echo "[pre-push] ERROR: $1" >&2
}

log_warn() {
    echo "[pre-push] WARN: $1"
}

log_step() {
    echo ""
    echo "=========================================="
    echo "[pre-push] $1"
    echo "=========================================="
}

# =============================================================================
# Bypass mechanism - allows users to skip hooks when needed
# =============================================================================
if [ -n "$BYPASS_ENV_VAR" ]; then
    log_warn "WRANGLER_SKIP_HOOKS is set - bypassing pre-push checks"
    log_warn "Use this sparingly (e.g., emergency fixes)"
    exit 0
fi

# =============================================================================
# Check if setup is complete (handles empty projects)
# =============================================================================
if [ -f ".wrangler/config/hooks-config.json" ]; then
    SETUP_COMPLETE=$(grep -o '"setupComplete"[[:space:]]*:[[:space:]]*true' .wrangler/config/hooks-config.json || echo "false")

    if [ "$SETUP_COMPLETE" = "false" ]; then
        log_info "Git hooks inactive (no tests configured yet)"
        log_info "Run /wrangler:update-git-hooks after adding tests"
        exit 0
    fi
fi

# =============================================================================
# Check if test command is configured
# =============================================================================
if [ -z "$TEST_COMMAND" ] || [ "$TEST_COMMAND" = "{{TEST_COMMAND}}" ]; then
    log_warn "No test command configured - skipping pre-push tests"
    log_warn "Configure via .wrangler/config/hooks-config.json"
    exit 0
fi

# =============================================================================
# Parse protected branch patterns
# =============================================================================
get_protected_branches() {
    # Default protected branches if not configured
    if [ -z "$PROTECTED_BRANCHES" ] || [ "$PROTECTED_BRANCHES" = "{{PROTECTED_BRANCHES}}" ]; then
        echo "main master develop release/* hotfix/*"
    else
        echo "$PROTECTED_BRANCHES"
    fi
}

# Check if branch matches any protected pattern
is_protected_branch() {
    local branch="$1"
    local patterns
    patterns=$(get_protected_branches)

    for pattern in $patterns; do
        case "$branch" in
            $pattern)
                return 0
                ;;
        esac
    done

    return 1
}

# =============================================================================
# Read refs from stdin and check for protected branches
# =============================================================================
log_info "Checking push to remote: $REMOTE ($URL)"

protected_push=false
target_branches=""

while read local_ref local_sha remote_ref remote_sha; do
    if [ -z "$local_ref" ]; then
        continue
    fi

    # Extract branch name from ref (refs/heads/branch-name -> branch-name)
    branch_name="${remote_ref#refs/heads/}"

    log_info "Push: $local_ref -> $remote_ref"

    if is_protected_branch "$branch_name"; then
        protected_push=true
        target_branches="$target_branches $branch_name"
        log_info "Protected branch detected: $branch_name"
    fi
done

# =============================================================================
# Run tests if pushing to protected branch
# =============================================================================
if [ "$protected_push" = true ]; then
    log_step "Running full test suite for protected branch push"
    log_info "Target branches:$target_branches"
    log_info "Test command: $TEST_COMMAND"
    echo ""

    start_time=$(date +%s)

    if eval "$TEST_COMMAND"; then
        end_time=$(date +%s)
        duration=$((end_time - start_time))
        log_success "All tests passed (${duration}s)"
        log_success "Push to protected branch$target_branches approved"
    else
        log_error "Tests failed - push blocked"
        log_error ""
        log_error "Protected branches require all tests to pass before pushing."
        log_error ""
        log_error "To fix:"
        log_error "  1. Review test output above"
        log_error "  2. Fix all failing tests"
        log_error "  3. Commit fixes"
        log_error "  4. Try push again"
        log_error ""
        log_error "Protected branch patterns:"
        for pattern in $(get_protected_branches); do
            log_error "  - $pattern"
        done
        log_error ""
        log_error "To bypass (use only for emergencies):"
        log_error "  WRANGLER_SKIP_HOOKS=1 git push"
        log_error ""
        log_error "Note: AI agents cannot use this bypass - only humans."
        exit 1
    fi
else
    log_info "No protected branches in this push - skipping full test suite"
    log_info "Protected branch patterns:"
    for pattern in $(get_protected_branches); do
        log_info "  - $pattern"
    done
fi

# =============================================================================
# Success
# =============================================================================
log_success "Pre-push checks passed - proceeding with push"
exit 0
